<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260625104550 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE audio_files (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(90) NOT NULL, description VARCHAR(255) NOT NULL, storage_key TEXT NOT NULL, duration_ms INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE chapters (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, chapter_order INT NOT NULL, description TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE complements (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, phonetic_list TEXT[] NOT NULL, constraint_tag_id_id INT NOT NULL, audio_path_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3A429FA02FBC9F91 ON complements (constraint_tag_id_id)');
        $this->addSql('CREATE INDEX IDX_3A429FA08A726784 ON complements (audio_path_id_id)');
        $this->addSql('CREATE TABLE constraint_tags (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(40) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE grapheme_types (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE graphemes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, min VARCHAR(5) NOT NULL, maj VARCHAR(5) NOT NULL, word VARCHAR(50) NOT NULL, is_silent_letter BOOLEAN NOT NULL, phonetic_list TEXT[] NOT NULL, module_id_id INT NOT NULL, audio_path_id INT NOT NULL, visual_trap_id INT DEFAULT NULL, type_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_22AEF8147648EE39 ON graphemes (module_id_id)');
        $this->addSql('CREATE INDEX IDX_22AEF814E6DB5FB7 ON graphemes (audio_path_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_22AEF8149605BA12 ON graphemes (visual_trap_id)');
        $this->addSql('CREATE INDEX IDX_22AEF814714819A0 ON graphemes (type_id_id)');
        $this->addSql('CREATE TABLE lessons (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, payload JSON NOT NULL, generated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(50) NOT NULL, user_id_id INT NOT NULL, module_id_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3F4218D99D86650F ON lessons (user_id_id)');
        $this->addSql('CREATE INDEX IDX_3F4218D97648EE39 ON lessons (module_id_id)');
        $this->addSql('CREATE TABLE levels (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(15) NOT NULL, description TEXT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE module_complements (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, module_id_id INT NOT NULL, complement_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B46995727648EE39 ON module_complements (module_id_id)');
        $this->addSql('CREATE INDEX IDX_B4699572CC99B2A9 ON module_complements (complement_id_id)');
        $this->addSql('CREATE TABLE module_subjects (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, module_id_id INT NOT NULL, subject_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CFE54AE97648EE39 ON module_subjects (module_id_id)');
        $this->addSql('CREATE INDEX IDX_CFE54AE96ED75F8F ON module_subjects (subject_id_id)');
        $this->addSql('CREATE TABLE module_verbs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, module_id_id INT NOT NULL, verb_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7CF600B07648EE39 ON module_verbs (module_id_id)');
        $this->addSql('CREATE INDEX IDX_7CF600B0B8CB410B ON module_verbs (verb_id_id)');
        $this->addSql('CREATE TABLE modules (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, module_order INT NOT NULL, description TEXT[] NOT NULL, content_version INT NOT NULL, chapter_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2EB743D7FF0D08E8 ON modules (chapter_id_id)');
        $this->addSql('CREATE TABLE person_numbers (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(15) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE progression (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id_id INT NOT NULL, module_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D5B250739D86650F ON progression (user_id_id)');
        $this->addSql('CREATE INDEX IDX_D5B250737648EE39 ON progression (module_id_id)');
        $this->addSql('CREATE TABLE refresh_tokens (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9BACE7E1C74F2195 ON refresh_tokens (refresh_token)');
        $this->addSql('CREATE TABLE session_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, raw_events JSON NOT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, processed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id_id INT NOT NULL, module_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F2E6F0FF9D86650F ON session_log (user_id_id)');
        $this->addSql('CREATE INDEX IDX_F2E6F0FF7648EE39 ON session_log (module_id_id)');
        $this->addSql('CREATE TABLE subjects (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, phonetic_list TEXT[] NOT NULL, person_id_id INT NOT NULL, audio_path_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AB259917D3728193 ON subjects (person_id_id)');
        $this->addSql('CREATE INDEX IDX_AB2599178A726784 ON subjects (audio_path_id_id)');
        $this->addSql('CREATE TABLE trophy (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, perfect_chapter INT NOT NULL, module_master INT NOT NULL, flawless_streak INT NOT NULL, update_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_112AFAE9A76ED395 ON trophy (user_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, telephone VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, last_name VARCHAR(255) DEFAULT NULL, first_name VARCHAR(255) DEFAULT NULL, birthday_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, register_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, update_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_TELEPHONE ON "user" (telephone)');
        $this->addSql('CREATE TABLE user_devices (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, os_name VARCHAR(120) NOT NULL, os_version VARCHAR(150) NOT NULL, app_version INT NOT NULL, user_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_490A50909D86650F ON user_devices (user_id_id)');
        $this->addSql('CREATE TABLE user_item_mastery (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, item_type VARCHAR(50) NOT NULL, item_id BIGINT NOT NULL, mastery_score NUMERIC(4, 3) NOT NULL, avg_response_ms INT NOT NULL, error_count INT NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1FD702019D86650F ON user_item_mastery (user_id_id)');
        $this->addSql('CREATE TABLE user_module_progress (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, global_score NUMERIC(4, 3) NOT NULL, consecutive_perfect_scores INT NOT NULL, ease_factor NUMERIC(4, 3) NOT NULL, interval_days INT NOT NULL, target_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, window_start_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, window_end_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(50) NOT NULL, last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id_id INT NOT NULL, module_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_541D4D379D86650F ON user_module_progress (user_id_id)');
        $this->addSql('CREATE INDEX IDX_541D4D377648EE39 ON user_module_progress (module_id_id)');
        $this->addSql('CREATE TABLE user_streaks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, longest_streak INT NOT NULL, last_activity_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1A8C376A76ED395 ON user_streaks (user_id)');
        $this->addSql('CREATE TABLE verbs (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(150) NOT NULL, phonetic_list TEXT[] NOT NULL, constraint_tag_id_id INT NOT NULL, person_id_id INT NOT NULL, audio_path_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75FA70DE2FBC9F91 ON verbs (constraint_tag_id_id)');
        $this->addSql('CREATE INDEX IDX_75FA70DED3728193 ON verbs (person_id_id)');
        $this->addSql('CREATE INDEX IDX_75FA70DE8A726784 ON verbs (audio_path_id_id)');
        $this->addSql('CREATE TABLE visual_trap (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name TEXT NOT NULL, list TEXT[] NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE words (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, word VARCHAR(100) NOT NULL, segmentation TEXT[] NOT NULL, phonetic_list TEXT[] NOT NULL, is_syllable BOOLEAN NOT NULL, is_sight_word BOOLEAN NOT NULL, audio_path_id INT NOT NULL, level_id_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_717D1E8CE6DB5FB7 ON words (audio_path_id)');
        $this->addSql('CREATE INDEX IDX_717D1E8C159D9B5E ON words (level_id_id)');
        $this->addSql('ALTER TABLE complements ADD CONSTRAINT FK_3A429FA02FBC9F91 FOREIGN KEY (constraint_tag_id_id) REFERENCES constraint_tags (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE complements ADD CONSTRAINT FK_3A429FA08A726784 FOREIGN KEY (audio_path_id_id) REFERENCES audio_files (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE graphemes ADD CONSTRAINT FK_22AEF8147648EE39 FOREIGN KEY (module_id_id) REFERENCES modules (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE graphemes ADD CONSTRAINT FK_22AEF814E6DB5FB7 FOREIGN KEY (audio_path_id) REFERENCES audio_files (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE graphemes ADD CONSTRAINT FK_22AEF8149605BA12 FOREIGN KEY (visual_trap_id) REFERENCES visual_trap (id)');
        $this->addSql('ALTER TABLE graphemes ADD CONSTRAINT FK_22AEF814714819A0 FOREIGN KEY (type_id_id) REFERENCES grapheme_types (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lessons ADD CONSTRAINT FK_3F4218D99D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lessons ADD CONSTRAINT FK_3F4218D97648EE39 FOREIGN KEY (module_id_id) REFERENCES modules (id)');
        $this->addSql('ALTER TABLE module_complements ADD CONSTRAINT FK_B46995727648EE39 FOREIGN KEY (module_id_id) REFERENCES modules (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE module_complements ADD CONSTRAINT FK_B4699572CC99B2A9 FOREIGN KEY (complement_id_id) REFERENCES complements (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE module_subjects ADD CONSTRAINT FK_CFE54AE97648EE39 FOREIGN KEY (module_id_id) REFERENCES modules (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE module_subjects ADD CONSTRAINT FK_CFE54AE96ED75F8F FOREIGN KEY (subject_id_id) REFERENCES subjects (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE module_verbs ADD CONSTRAINT FK_7CF600B07648EE39 FOREIGN KEY (module_id_id) REFERENCES modules (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE module_verbs ADD CONSTRAINT FK_7CF600B0B8CB410B FOREIGN KEY (verb_id_id) REFERENCES verbs (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE modules ADD CONSTRAINT FK_2EB743D7FF0D08E8 FOREIGN KEY (chapter_id_id) REFERENCES chapters (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE progression ADD CONSTRAINT FK_D5B250739D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE progression ADD CONSTRAINT FK_D5B250737648EE39 FOREIGN KEY (module_id_id) REFERENCES modules (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session_log ADD CONSTRAINT FK_F2E6F0FF9D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session_log ADD CONSTRAINT FK_F2E6F0FF7648EE39 FOREIGN KEY (module_id_id) REFERENCES modules (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subjects ADD CONSTRAINT FK_AB259917D3728193 FOREIGN KEY (person_id_id) REFERENCES person_numbers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE subjects ADD CONSTRAINT FK_AB2599178A726784 FOREIGN KEY (audio_path_id_id) REFERENCES audio_files (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE trophy ADD CONSTRAINT FK_112AFAE9A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_devices ADD CONSTRAINT FK_490A50909D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_item_mastery ADD CONSTRAINT FK_1FD702019D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_module_progress ADD CONSTRAINT FK_541D4D379D86650F FOREIGN KEY (user_id_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_module_progress ADD CONSTRAINT FK_541D4D377648EE39 FOREIGN KEY (module_id_id) REFERENCES modules (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_streaks ADD CONSTRAINT FK_1A8C376A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE verbs ADD CONSTRAINT FK_75FA70DE2FBC9F91 FOREIGN KEY (constraint_tag_id_id) REFERENCES constraint_tags (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE verbs ADD CONSTRAINT FK_75FA70DED3728193 FOREIGN KEY (person_id_id) REFERENCES person_numbers (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE verbs ADD CONSTRAINT FK_75FA70DE8A726784 FOREIGN KEY (audio_path_id_id) REFERENCES audio_files (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE words ADD CONSTRAINT FK_717D1E8CE6DB5FB7 FOREIGN KEY (audio_path_id) REFERENCES audio_files (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE words ADD CONSTRAINT FK_717D1E8C159D9B5E FOREIGN KEY (level_id_id) REFERENCES levels (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE complements DROP CONSTRAINT FK_3A429FA02FBC9F91');
        $this->addSql('ALTER TABLE complements DROP CONSTRAINT FK_3A429FA08A726784');
        $this->addSql('ALTER TABLE graphemes DROP CONSTRAINT FK_22AEF8147648EE39');
        $this->addSql('ALTER TABLE graphemes DROP CONSTRAINT FK_22AEF814E6DB5FB7');
        $this->addSql('ALTER TABLE graphemes DROP CONSTRAINT FK_22AEF8149605BA12');
        $this->addSql('ALTER TABLE graphemes DROP CONSTRAINT FK_22AEF814714819A0');
        $this->addSql('ALTER TABLE lessons DROP CONSTRAINT FK_3F4218D99D86650F');
        $this->addSql('ALTER TABLE lessons DROP CONSTRAINT FK_3F4218D97648EE39');
        $this->addSql('ALTER TABLE module_complements DROP CONSTRAINT FK_B46995727648EE39');
        $this->addSql('ALTER TABLE module_complements DROP CONSTRAINT FK_B4699572CC99B2A9');
        $this->addSql('ALTER TABLE module_subjects DROP CONSTRAINT FK_CFE54AE97648EE39');
        $this->addSql('ALTER TABLE module_subjects DROP CONSTRAINT FK_CFE54AE96ED75F8F');
        $this->addSql('ALTER TABLE module_verbs DROP CONSTRAINT FK_7CF600B07648EE39');
        $this->addSql('ALTER TABLE module_verbs DROP CONSTRAINT FK_7CF600B0B8CB410B');
        $this->addSql('ALTER TABLE modules DROP CONSTRAINT FK_2EB743D7FF0D08E8');
        $this->addSql('ALTER TABLE progression DROP CONSTRAINT FK_D5B250739D86650F');
        $this->addSql('ALTER TABLE progression DROP CONSTRAINT FK_D5B250737648EE39');
        $this->addSql('ALTER TABLE session_log DROP CONSTRAINT FK_F2E6F0FF9D86650F');
        $this->addSql('ALTER TABLE session_log DROP CONSTRAINT FK_F2E6F0FF7648EE39');
        $this->addSql('ALTER TABLE subjects DROP CONSTRAINT FK_AB259917D3728193');
        $this->addSql('ALTER TABLE subjects DROP CONSTRAINT FK_AB2599178A726784');
        $this->addSql('ALTER TABLE trophy DROP CONSTRAINT FK_112AFAE9A76ED395');
        $this->addSql('ALTER TABLE user_devices DROP CONSTRAINT FK_490A50909D86650F');
        $this->addSql('ALTER TABLE user_item_mastery DROP CONSTRAINT FK_1FD702019D86650F');
        $this->addSql('ALTER TABLE user_module_progress DROP CONSTRAINT FK_541D4D379D86650F');
        $this->addSql('ALTER TABLE user_module_progress DROP CONSTRAINT FK_541D4D377648EE39');
        $this->addSql('ALTER TABLE user_streaks DROP CONSTRAINT FK_1A8C376A76ED395');
        $this->addSql('ALTER TABLE verbs DROP CONSTRAINT FK_75FA70DE2FBC9F91');
        $this->addSql('ALTER TABLE verbs DROP CONSTRAINT FK_75FA70DED3728193');
        $this->addSql('ALTER TABLE verbs DROP CONSTRAINT FK_75FA70DE8A726784');
        $this->addSql('ALTER TABLE words DROP CONSTRAINT FK_717D1E8CE6DB5FB7');
        $this->addSql('ALTER TABLE words DROP CONSTRAINT FK_717D1E8C159D9B5E');
        $this->addSql('DROP TABLE audio_files');
        $this->addSql('DROP TABLE chapters');
        $this->addSql('DROP TABLE complements');
        $this->addSql('DROP TABLE constraint_tags');
        $this->addSql('DROP TABLE grapheme_types');
        $this->addSql('DROP TABLE graphemes');
        $this->addSql('DROP TABLE lessons');
        $this->addSql('DROP TABLE levels');
        $this->addSql('DROP TABLE module_complements');
        $this->addSql('DROP TABLE module_subjects');
        $this->addSql('DROP TABLE module_verbs');
        $this->addSql('DROP TABLE modules');
        $this->addSql('DROP TABLE person_numbers');
        $this->addSql('DROP TABLE progression');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE session_log');
        $this->addSql('DROP TABLE subjects');
        $this->addSql('DROP TABLE trophy');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_devices');
        $this->addSql('DROP TABLE user_item_mastery');
        $this->addSql('DROP TABLE user_module_progress');
        $this->addSql('DROP TABLE user_streaks');
        $this->addSql('DROP TABLE verbs');
        $this->addSql('DROP TABLE visual_trap');
        $this->addSql('DROP TABLE words');
    }
}
