
security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: telephone

    firewalls:
        dev:
            # Ensure dev tools and static assets are always allowed
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        
        # 1. Le pare-feu pour se connecter (génère les premiers tokens)
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login # La route appelée par React Native
                username_path: telephone # Remplace par email si tu utilises l'email au lieu du téléphone
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # 2. Le pare-feu pour renouveler les tokens
        api_token_refresh:
            pattern: ^/api/token/refresh
            stateless: true
            refresh_jwt:
                check_path: /api/token/refresh

        # 3. Le pare-feu global qui protège toute ton API
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        # On laisse tout le monde tenter de se connecter ou de rafraîchir le token
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/ping, roles: PUBLIC_ACCESS }
        - { path: ^/api/token/refresh, roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        
        # On verrouille ABSOLUMENT tout le reste de l'API
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon